In [36]:
import pandas as pd
import numpy as np
import itertools

In [19]:
def expand_grid(data_dict):
    rows = itertools.product(*data_dict.values())
    return pd.DataFrame.from_records(rows, columns=data_dict.keys())

In [20]:
df = expand_grid(
    {'height': [60, 70],
     'weight': [100, 140, 180],
     'sex': ['Male', 'Female']})

In [24]:
df.as_matrix()

array([[60, 100, 'Male'],
       [60, 100, 'Female'],
       [60, 140, 'Male'],
       [60, 140, 'Female'],
       [60, 180, 'Male'],
       [60, 180, 'Female'],
       [70, 100, 'Male'],
       [70, 100, 'Female'],
       [70, 140, 'Male'],
       [70, 140, 'Female'],
       [70, 180, 'Male'],
       [70, 180, 'Female']], dtype=object)

In [28]:
from collections import Counter
z = ['blue', 'red', 'blue', 'yellow', 'blue', 'red', 'yellow']

In [29]:
Counter(z)

Counter({'blue': 3, 'red': 2, 'yellow': 2})

In [30]:
l = {'haus': [1,2,3]}

In [35]:
l.values()

dict_values([[1, 2, 3]])

In [38]:
n = np.array([[1,2,3], [2,3,5], [4,3,5]])

In [39]:
n

array([[1, 2, 3],
       [2, 3, 5],
       [4, 3, 5]])

In [43]:
w = np.array([0.1,0.1,0.1])

In [44]:
w.dot(n)

array([ 0.7,  0.8,  1.3])

In [45]:
np.cov(n)

array([[ 1.        ,  1.5       ,  0.5       ],
       [ 1.5       ,  2.33333333,  1.        ],
       [ 0.5       ,  1.        ,  1.        ]])