In [1]:
import numpy as np

In [17]:
A = np.array([[1],[2],[3]])

In [18]:
A

array([[1],
       [2],
       [3]])

In [24]:
b = np.array([[1,2]])

In [25]:
b

array([[1, 2]])

In [26]:
A.dot(b)

array([[1, 2],
       [2, 4],
       [3, 6]])